### ISSUE TITLE
[Feature] ADD NEW CONDITION TYPE

### ISSUE THREAD

**Issue by SkyDude0** [Lorenzo0111/RocketPlaceholders#158]
Hi, it would be nice if you can add new condition type related to placeholders!

Config example:

```
    conditions:
      PlaceholderExample:
        type: PLACEHOLDER
        value: "%another_plugin_placeholder% (=/!=/>=/<=) Example_outuput"
        text: "Example value"
```

So.. If PAPI match the outuput, it return a different value.
