### ISSUE TITLE
[Feature] PAPI Conditions Support

### ISSUE THREAD

**Issue by SuperBeacon** [Lorenzo0111/RocketPlaceholders#161]
**What type of feature is it?**
_Put an x in a option, like [x]_

- [ ] New Command
- [x] Config option
- [ ] Other
I hope Custom Conditions can support PAPI Conditions, for example:
*1
conditions:
papiExample:
type: PAPI
PAPI: %playerpoints_points%
value: <10
text: "Example condition text"
*2
conditions:
papiExample:
type: PAPI
PAPI: %playerpoints_points%
value: =10
text: "Example condition text"
*3
conditions:
papiExample:
type: PAPI
PAPI: %playerpoints_points%
value: >=10
text: "Example condition text"
*4
conditions:
papiExample:
type: PAPI
PAPI: %player_name%
value: testname
text: "Example condition text"

**Comment by Lorenzo0111** [comment]
You can use the javascript condition to exactly do that

**Comment by SuperBeacon** [comment]
Oh, okay, I hope you can write an example in the wiki

**Comment by Lorenzo0111** [comment]
Something like this

```yml
    exampleCondition:
        type: JAVASCRIPT
        value: "%playerpoints_points% < 10"
        text: "Example condition text"
```
